apps/users/urls.py
from django.conf.urls import patterns, include, url
from apps.users import views
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',

    url(r'^profile/(?P<username>[^/]+)$', views.profile, name='profile'),
    url(r'^dashboard$', views.dashboard, name='dashboard'),
    url(r'^home/$', views.success, name='success'),
    url(r'^parapo/$', views.parapo, name='parapo'),
    url(r'^reports/$', views.reports, name='reports'),
    url(r'^reports/new/$', views.create_report, name='create_report'),
)

core/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
import resource


urlpatterns = patterns('',
    # Examples:
    url(r'', include('apps.home.urls')),
    url(r'', include('apps.users.urls', namespace='staff')),

    # Register Home Views
    # url(r'^$', include(core.urls)),

    # Register Admin Views
    url(r'^admin/', include(admin.site.urls)),

    # url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'home/login.html'}, name='login'),
    url(r'', include('social_auth.urls')),

    # API routes definition
    url(r'^api/v1/auth', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/v1/', include(resource.urls))
)

apps/report/models.py
from django.db import models
from apps.users.models import Staff

# Create your models here.
class Report(models.Model):

    content = models.TextField()
    challenges = models.TextField(default='loremsjhsfb jhsb jsfbjhfdbjhfbhjb ')
    achievements = models.TextField(default='loremsjhsfb jhsb jsfbjhfdbjhfbhjb ')
    plans = models.TextField(default='loremsjhsfb jhsb jsfbjhfdbjhfbhjb ')
    creator = models.ForeignKey(Staff, related_name='reports')

    class Meta:
        verbose_name = "Report"
        verbose_name_plural = "Reports"



class Review(models.Model):

    text = models.TextField()
    reviewer = models.ForeignKey(Staff, related_name='reviews')
    report = models.ForeignKey(Report, related_name='reviews')


    class Meta:
        verbose_name = "Review"
        verbose_name_plural = "Reviews"



class Comment(models.Model):

    text = models.TextField()
    author = models.ForeignKey(Staff, related_name='comments')
    review = models.ForeignKey(Review, related_name='comments')

    class Meta:
        verbose_name = "Comment"
        verbose_name_plural = "Comments"


class Tag(models.Model):

    word = models.CharField(max_length=30)

    class Meta:
        verbose_name = "Tag"
        verbose_name_plural = "Tags"

apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager, Permission
from django.utils.translation import ugettext, ugettext_lazy as _
from django.utils import six, timezone
from django.core.mail import send_mail

# Create your models here.
class StaffManager(models.Manager):

    """docstring for staffManager"""
    @classmethod
    def normalize_email(cls, email):
        """
        Normalize the address by lowercasing the domain part of the email
        address.
        """
        email = email or ''
        try:
            email_name, domain_part = email.strip().rsplit('@', 1)
        except ValueError:
            pass
        else:
            email = '@'.join([email_name, domain_part.lower()])
        return email

    def make_random_password(self, length=10,
                             allowed_chars='abcdefghjkmnpqrstuvwxyz'
                                           'ABCDEFGHJKLMNPQRSTUVWXYZ'
                                           '23456789'):
        """
        Generates a random password with the given length and given
        allowed_chars. Note that the default value of allowed_chars does not
        have "I" or "O" or letters and digits that look similar -- just to
        avoid confusion.
        """
        return get_random_string(length, allowed_chars)

    def get_by_natural_key(self, username):
        return self.get(**{self.model.USERNAME_FIELD: username})

    def _create_user(self, username, email, password,
                     is_staff, is_superuser, **extra_fields):
        """
        Creates and saves a User with the given username, email and password.
        """
        now = timezone.now()
        if not username:
            raise ValueError('The given username must be set')
        email = self.normalize_email(email)
        user = self.model(username=username, email=email,
                          is_staff=is_staff, is_active=True,
                          is_superuser=is_superuser,
                          date_joined=now,
                          **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password, **extra_fields):
        return self._create_user(username, email, password, True, True,
                                 **extra_fields)

    def create_user(self, username, email=None, password=None, **extra_fields):
        username = email.split('@')[0]
        return self._create_user(username, email, password, False, False,
                                 **extra_fields)

    def get_names(self):
        staff_members = []
        obj = self.all()
        for staff in obj:
            staff_members.append("{} {}".format(staff.first_name, staff.last_name))
        return staff_members



class Staff(AbstractBaseUser, PermissionsMixin):

    username = models.CharField(_('username'), max_length=30, unique=True)
    first_name = models.CharField(_('first name'), max_length=45, blank=True)
    last_name = models.CharField(_('last name'), max_length=30, blank=True)
    email = models.EmailField(_('email address'), unique=True)
    gender = models.CharField(max_length=16, blank=True)
    picture = models.CharField(max_length=255, blank=True)
    is_staff = models.BooleanField(_('staff status'), default=False,
        help_text=_('Designates whether the user can log into this admin '
                    'site.'))
    is_active = models.BooleanField(_('active'), default=True,
        help_text=_('Designates whether this user should be treated as '
                    'active. Unselect this instead of deleting accounts.'))
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = StaffManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    class Meta:
        """docstring for Meta"""
        verbose_name = _('staff')
        verbose_name_plural = _('staff')

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        "Returns the short name for the user."
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """
        Sends an email to this User.
        """
        send_mail(subject, message, from_email, [self.email], **kwargs)


class Parapo(models.Model):

    rant = models.TextField()
    staff = models.ForeignKey(Staff, related_name='rants')

    class Meta:
        verbose_name = "Parapo"
        verbose_name_plural = "Parapos"


class TeamManager(models.Manager):
    """
    The manager for the auth's Group model.
    """
    use_in_migrations = True

    def get_by_natural_key(self, name):
        return self.get(name=name)

    def get_teams(self):
        obj = self.all()
        teams = {}
        for team in obj:
            teams.update({'name':team.name, 'lead':team.lead})

        return teams


class Team(models.Model):

    name = models.CharField(_('name'), max_length=80, unique=True)
    permissions = models.ManyToManyField(Permission,
        verbose_name=_('permissions'), blank=True)
    lead = models.ForeignKey(Staff, related_name='crews')

    objects = TeamManager()

    class Meta:
        verbose_name = _('team')
        verbose_name_plural = _('teams')

    def __str__(self):
        return self.name

    def natural_key(self):
        return (self.name,)

apps/report/views.py
from django.shortcuts import render

# Create your views here.

apps/users/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from apps.users.models import Staff
from django.shortcuts import get_object_or_404


# Create your views here.
@login_required
def profile(request, username):
    # return HttpResponse('Welcome, ' + username)
    user = get_object_or_404(Staff, username=username)
    return render(request, 'users/index.html', locals())

@login_required
def dashboard(request):
    obj = request.user
    user = get_object_or_404(Staff, username=obj.username)
    return render(request, 'users/index.html', locals())


@login_required
def success(request):
    print request.user
    return render(request, 'users/index.html', locals())


@login_required
def parapo(request):
    return render(request, 'users/parapo.html', locals())


def reports(request):
    return render(request, 'users/reports.html', locals())


def create_report(request):
    return render(request, 'users/create_report.html', locals())

apps/users/templates/users/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
  <title>Reportr: Dashboard</title>

  <!-- CSS  -->
  <link href="{% static 'users/css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="{% static 'users/css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
<style type="text/css">
  a{
    text-transform: none;
  }
</style>
  {% block localcss %}

  {% endblock localcss %}
</head>
<body>
  <header class='navbar-fixed'>
  <nav class="white navbar-fixed " id="front-page-nav " role="navigation">
    <div class="">
      <div class="nav-wrapper">
        <a id="logo-container" href="#" class="brand-logo"><img src="{% static 'images/logo2.png' %}" id="front-page-logo" alt="Andela Logo"></a>
        <!-- Dropdown Structure -->
        <ul id="dropdown1" class="dropdown-content">
          <li><a href="#" class="black-text text-lighten-1">Profile</a></li>
          <li><a href="#" class="black-text text-lighten-1">Questions</a></li>
          <li class="divider"></li>
          <li><a href="#!" class="red-text text-lighten-2">Logout</a></li>
        </ul>
        <ul id="dropdown2" class="dropdown-content">
          <li class="divider"></li>
          <li><a href="#!" onclick="toast('Yet to be implemented.', 2000)">Edit</a></li>
        </ul>
        <ul class="right">
          <li class="active">
            <a class="red-text show-on-large text-lighten-2" href="{% url 'staff:dashboard' %}">Dashboard</a>
          </li>
          <li>
            <a class="red-text hide-on-small-only hide-on-med-only text-lighten-2" href="#!" onclick="toast('Yet to be implemented.', 2000)">Playbooks</a>
          </li>
          <li>
            <a class="red-text hide-on-small-only hide-on-med-only text-lighten-2" href="{% url 'staff:reports' %}">Reports</a>
          </li>
          <li>
            <a class="mdi-communication-email purple-text show-on-large text-darken-2" onclick="toast('Yet to be implemented.', 2000)" href="#!">12</a>
          </li>
          <li>
            <a class="mdi-action-account-circle red-text hide-on-small-only hide-on-med-only text-lighten-2 dropdown-button" href="#!" data-activates="dropdown1">{{ user.first_name }} <i class="mdi-navigation-arrow-drop-down right"></i>
            </a>
          </li>
        </ul>
        <ul id="nav-mobile" class="right side-nav">
          <li><a href="#" disabled><h4>Menu</h4></a></li>
          <li><a href="{% url 'staff:dashboard' %}">Dashboard</a></li>
          <li><a href="#">Profile</a></li>
          <li><a href="#">Questions</a></li>
          <li><a href="#">Playbooks</a></li>
          <li><a href="#">Reports</a></li>
          <li class="divider"></li>
          <li><a href="#!">Logout</a></li>
        </ul>
        <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="mdi-navigation-menu red-text text-lighten-2"></i></a>
      </div>
    </div>
  </nav>
  </header>
  <main>
    <div class="">
      <div class="row">
        <div class="col s12 m12 offset-l1 l10">
          <div class="row">
          {% block content %}

          {% endblock content %}
          </div>
        </div>
        <!-- Edit Buttons -->
        <div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
          <a class="btn-floating btn-large red lighten-2">
            <i class="large mdi-editor-border-color"></i>
          </a>
          <ul>
            <li><a class="btn-floating purple lighten-3"><i title='Create a playbook Entry' class="large mdi-action-alarm-add" onclick="toast('Yet to be implemented.', 2000)"></i></a></li>
            <li><a href="{% url 'staff:create_report' %}" class="btn-floating blue-grey darken-4" title="Write a Report"><i class="large mdi-action-description"></i></a></li>
          </ul>
        </div>
        <!-- End Edit Button -->
      </div>
    </div>
  </main>
  <footer class="page-footer red center-align lighten-2">
    <div class="footer-copyright">
      <div class="container">
      Made with &#x2665; by <a href="http://twitter.com/" style="color:#ddd">Judith</a> and <a style="color:#ddd" href="http://twitter.com/ojengwa_">Bernard</a>.
      </div>
    </div>
  </footer>


  <!--  Scripts-->
  <script src="{% static "users/js/jquery.js" %}"></script>
    <script src="{% static "users/js/jquery.timeago.min.js" %}"></script>
  <script src="{% static "users/js/materialize.js" %}"></script>
    <script src="{% static "users/js/prism.js" %}"></script>
  <script src="{% static "users/js/init.js" %}"></script>
  <script>
  $(document).ready(function() {
    $(".dropdown-button").dropdown();
    $('.collapsible').collapsible({
      accordion : true
    });
  });
  </script>
  {% block localjs %}

  {% endblock localjs %}
  </body>
</html>

apps/users/templates/users/create_report.html
{% extends "users/base.html" %}
{% block localcss %}
  <style type="text/css">
    .no-box-shadow {
      box-shadow: none;
    }
  </style>
{% endblock localcss %}
{% block content %}
<div class="col s12 m12 l12">
  <div class="card  lighten-4">
    <div class="card-content black-text">
      <div class="row  card lighten-4 no-box-shadow">
        <div class=" col s12 m12 l12">
          <span class="card-title black-text text-lighten-2">Weekly Report</span>
          <div class="divider"></div>
          <div class="card-content">
          <div class="row">
            <form class="col offset-l1 s12 m12 l10">
              <div class="row">
                <div class="input-field col s12 m12 l12">
                  <textarea id="icon_prefix2" class="materialize-textarea"></textarea>
                  <label for="icon_prefix2">What challenges are you facing? How did you fix or intend to fix that?</label>
                </div>
                <div class="input-field col s12 m12 l12">
                  <textarea id="good" class="materialize-textarea"></textarea>
                  <label for="good">What are your achievements in your role this week? <small class='red-text text-lighten-2'>one per line</small> </label>
                </div>
                <div class="input-field col s12 m12 l12">
                  <textarea id="icon" class="materialize-textarea"></textarea>
                  <label for="icon">What are your plans for next week? How do they align with your <strong class='red-text text-lighten-2'>OKRs</strong>?</label>
                </div>
                <div class="input-field col right s10 offset-s2 m2 l2">
                  <button class="btn waves-effect red lighten-2 no-box-shadow waves-light" type="submit" name="action">Share
                    <i class="mdi-content-send "></i>
                  </button>
                </div>
              </div>
            </form>
          </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

apps/users/templates/users/index.html
{% extends "users/base.html" %}
{% block localcss %}
  <style type="text/css">
    .no-box-shadow {
      box-shadow: none;
    }
    .linky{
      text-transform: none;
      color: black;
    }
  </style>
{% endblock localcss %}
{% block content %}
<div class="col s12 m12 l12">
  <div class="card grey lighten-4">
    <div class="card-content black-text">
      <div class="row grey card lighten-4 no-box-shadow">
        <div class="col s12 m6 l6">
          <span class="card-title grey-text">Freckle Tracker</span>
          <div class="card-content">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
          cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
          proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          </div>
        </div>
        <div class=" col s12 m6 l6">
          <span class="card-title grey-text">Social Buzz</span>
          <div class="card-content">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
          cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
          proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          </div>
        </div>
        <div class=" col s12 m6 l6">
          <span class="card-title grey-text">Fellows</span>
          <div class="card-content">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
          cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
          proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          </div>
        </div>
        <div class=" col s12 m6 l6">
          <span class="card-title grey-text">OKRs</span>
          <div class="card-content">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
          cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
          proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          </div>
        </div>
      </div>
    </div>
    <div class="card-action">
      <a href="#">This is a link</a>
      <a href='#'>This is a link</a>
    </div>
  </div>
</div>
{% endblock content %}

apps/users/templates/users/parapo.html
{% extends "users/base.html" %}
{% block localcss %}
  <style type="text/css">
    .no-box-shadow {
      box-shadow: none;
    }
  </style>
{% endblock localcss %}
{% block content %}
<div class="col s12 m12 l12">
  <div class="card  lighten-4">
    <div class="card-content black-text">
      <div class="row  card lighten-4 no-box-shadow">
        <div class=" col s12 m12 l12">
          <span class="card-title black-text text-lighten-2">Weekly Report</span>
          <div class="divider"></div>
          <div class="card-content">
          <div class="row">
            <form class="col offset-l1 s12 m12 l10">
              <div class="row">
                <div class="input-field col s12 m12 l12">
                  <textarea id="icon_prefix2" class="materialize-textarea"></textarea>
                  <label for="icon_prefix2">What challenges are you facing? How do you fix intend to fix that?</label>
                </div>
                <div class="input-field col s12 m12 l12">
                  <textarea id="good" class="materialize-textarea"></textarea>
                  <label for="good">What's going well in your role this week?</label>
                </div>
                <div class="input-field col s12 m12 l12">
                  <textarea id="icon" class="materialize-textarea"></textarea>
                  <label for="icon">Any general suggestions on how to improve the commpany?</label>
                </div>
                <div class="input-field col right s10 offset-s2 m2 l2">
                  <button class="btn waves-effect red lighten-2 no-box-shadow waves-light" type="submit" name="action">Share
                    <i class="mdi-content-send "></i>
                  </button>
                </div>
              </div>
            </form>
          </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

apps/users/templates/users/reports.html
{% extends "users/base.html" %}
{% block localcss %}
  <style type="text/css">
    .no-box-shadow {
      box-shadow: none;
    }
  </style>
{% endblock localcss %}
{% block content %}
<div class="col s12 m12 l12">
  <div class="card  lighten-4">
    <div class="card-content black-text">
      <div class="row  card lighten-4 no-box-shadow">
        <div class=" col s12 m12 l12">
          <div class="card-title row black-text text-lighten-2">
            <div class="col s12 m4 l4 left"><h4 class="grey-text text-darken-2">Report Sheet</h4></div>
            <div class="input-field hide-on-small-only col s12 m5 l5 right">
              <i class="mdi-action-search prefix"></i><input id="search" placeholder='Filter Reports...' type="text">
            </div>
          </div>
          <div class="divider"></div>
          <div class="card-content">
          <div class="row">
          <div class="col s12">
            <ul class="tabs">
              <li class="tab col s3"><a href="#test1">My Reports</a></li>
              <li class="tab col s3"><a class="active" href="#test2">Tech Team</a></li>
              <li class="tab col s3"><a href="#test3">Other Teams</a></li>
              <li class="tab col s3"><a href="#test4">General</a></li>
            </ul>
          </div>
          <div id="test1" class="col s12">Test 1</div>
          <div id="test2" class="col s12">Test 2</div>
          <div id="test3" class="col s12">Test 3</div>
          <div id="test4" class="col s12">Test 4</div>
          </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block localjs %}
<script type="text/javascript">
    $(document).ready(function(){
      $('ul.tabs').tabs();
    });
</script>
{% endblock localjs %}